package package2;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import package1.TempAddUser;
import package2.validate;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Guddu
 */
public class RegistrationGUI extends javax.swing.JFrame {
	private Registration_Controller rc;
	private int i;

	/**
	 * Creates new form UserRegistration
	 */
	public RegistrationGUI() {
		initComponents();
		rc = new Registration_Controller(this);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblusername = new javax.swing.JLabel();
		lblfirstname = new javax.swing.JLabel();
		lbllastname = new javax.swing.JLabel();
		lblemailid = new javax.swing.JLabel();
		lblpassword = new javax.swing.JLabel();
		lblconfirmpassword = new javax.swing.JLabel();
		cmbrole = new javax.swing.JComboBox();
		txtusername = new javax.swing.JTextField();
		txtfirstname = new javax.swing.JTextField();
		txtlastname = new javax.swing.JTextField();
		txtemailid = new javax.swing.JTextField();
		lblrole = new javax.swing.JLabel();
		btnsignup = new javax.swing.JButton();
		txtpassword = new javax.swing.JPasswordField();
		txtconfirmpassword = new javax.swing.JPasswordField();
		lblphonenumber = new javax.swing.JLabel();
		txtphonenumber = new javax.swing.JTextField();
		javax.swing.ImageIcon imgIcon1 = new javax.swing.ImageIcon("fpl.jpg");
		imgLabel = new javax.swing.JLabel(imgIcon1);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblusername.setText("User Name");

		lblfirstname.setText("First Name");

		lbllastname.setText("Last Name");

		lblemailid.setText("E-mail ID");

		lblpassword.setText("Password");

		lblconfirmpassword.setText("Confirm Password");

		cmbrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User", "Admin", "Staff" }));

		txtfirstname.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtfirstnameActionPerformed(evt);
			}
		});

		txtlastname.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtlastnameActionPerformed(evt);
			}
		});

		btnsignup.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnsignupActionPerformed(evt);
			}
		});

		lblrole.setText("Role");

		btnsignup.setText("Sign Up!");

		lblphonenumber.setText("Phone Number");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(55,55,55)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblconfirmpassword)
												.addComponent(lblrole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(lblpassword)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addComponent(lblemailid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(lbllastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
														.addComponent(btnsignup)
														.addComponent(lblphonenumber))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(lblusername)
																.addGap(35, 35, 35)))
																.addComponent(lblfirstname))
																.addGap(162, 162, 162)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		.addComponent(txtfirstname)
																		.addComponent(txtusername)
																		.addComponent(txtlastname)
																		.addComponent(txtemailid)
																		.addComponent(cmbrole, 0, 104, Short.MAX_VALUE)
																		.addComponent(txtpassword)
																		.addComponent(txtconfirmpassword)
																		.addComponent(txtphonenumber))
																		.addGap(0, 378, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(135, 135, 135)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblusername)
								.addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblfirstname))
										.addGap(18, 18, 18)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lbllastname)
												.addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(lblemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(lblpassword)
																.addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18, 18)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(lblconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(txtconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18, 18, 18)
																		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(lblphonenumber)
																				.addComponent(txtphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(18, 18, 18)
																				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(lblrole)
																						.addComponent(cmbrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(18, 18, 18)
																						.addComponent(btnsignup)
																						.addContainerGap(72, Short.MAX_VALUE))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(36, 36, 36))
				);

		pack();
	}// </editor-fold> 

	void resetFields() {
		setUserNameTextField("");
		setFirstNameTextField("");
		setLastNameTextField("");
		setPasswordTextField("");
		setConfirmPasswordTextField("");
		setEmailTextField("");
		setPhoneNumberTextField("");
	}

	/* Courtesy: Google Search */
	boolean validatePhoneNumber(String phoneNumber) {
		//validate phone numbers of format "1234567890"
		if (phoneNumber.matches("\\d{10}")) return true;
		/*//validating phone number with -, . or spaces
	        else if(phoneNo.matches("\\d{3}[-\\.\\s]\\d{3}[-\\.\\s]\\d{4}")) return true;
	        //validating phone number with extension length from 3 to 5
	        else if(phoneNo.matches("\\d{3}-\\d{3}-\\d{4}\\s(x|(ext))\\d{3,5}")) return true;
	        //validating phone number where area code is in braces ()
	        else if(phoneNo.matches("\\(\\d{3}\\)-\\d{3}-\\d{4}")) return true;
	        //return false if nothing matches the input*/
		else {

			JOptionPane.showMessageDialog(null, "Phone Number is not valid. Phone number"
					+ " must be in the form xxxxxxxxxx", "Error",
					JOptionPane.ERROR_MESSAGE);
			// resetFields();
			return false;
		}
	}

	private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {                                             
		// TODO add your handling code here:
	}                                            

	private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
	}                                           

	/**
	 * @param args the command line arguments
	 */
	private void btnsignupActionPerformed(java.awt.event.ActionEvent evt){
		validate v1 = new validate();
		String msg = "";
		TempAddUser tua = null ;
		int tempCount = 0;
		String[] array=new String[8];
		if(getUserNameTextField()!=null && getUserNameTextField().length()!=0){
			array[0]=getUserNameTextField();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter UserName ";
		}
		if(getFirstNameTextField()!=null && getFirstNameTextField().length()!=0){
			array[1]=getFirstNameTextField();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter First Name ";
		}
		if(getLastNameTextField()!=null && getLastNameTextField().length()!=0){
			array[2]=getLastNameTextField();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter Last Name ";
		}
		if (getEmailTextField()!=null){
			array[3]=getEmailTextField();
			boolean valid = v1.isEmail(array[3]);
			if (valid == false) {
				JOptionPane.showMessageDialog(null, "Email is not valid. Email Id"
						+ " must be in the form xxx@xxx.xxx", "Error",
						JOptionPane.ERROR_MESSAGE);
				return;
			}
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter Valid Email";
		}
		if(getPasswordTextField()!=null && getPasswordTextField().length()!=0 ){
			array[4]=getPasswordTextField();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter Password ";
		}
		if(((getPasswordTextField()!=null) && (getConfirmPasswordTextField()!=null)) && getPasswordTextField().equals(getConfirmPasswordTextField())){
			array[5]=getConfirmPasswordTextField();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter same Confirm Password ";
		}
		if(getPhoneNumberTextField()!=null && getPhoneNumberTextField().length()!=0 ) {
			array[6]=getPhoneNumberTextField();
			boolean valid = validatePhoneNumber(array[6]);
			if (valid == false) return;
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Enter Phone Number ";
		}

		if(getRoleComboBox()!=null && v1.isSelected(getRoleComboBox())){
			array[7]=getRoleComboBox();
			tempCount ++;
		}
		else
		{
			msg = msg + "\n Select Role ";
		}
		//	if(array!=null){

		if(tempCount == 8)
		{
			tua = rc.addRow(array);       
		}
		else
		{
			JOptionPane.showMessageDialog(null, msg);
			return;
		}
		//}
		if(tua!=null)
		{
			resetFields();
			JOptionPane.showMessageDialog(null,"Registration Successfull");
		}




	}
	//methods to get text from text fields into the array

	public String getUserNameTextField() {
		return txtusername.getText();
	}
	public String getFirstNameTextField() {
		return txtfirstname.getText();
	} 
	public String getLastNameTextField() {
		return txtlastname.getText();
	} 
	public String getEmailTextField() {
		return txtemailid.getText();
	} 
	public String getPasswordTextField() {
		return txtpassword.getText();
	} 
	public String getConfirmPasswordTextField() {
		return txtconfirmpassword.getText();
	} 
	public String getPhoneNumberTextField() {
		return txtphonenumber.getText();
	} 
	public String getRoleComboBox() {
		return cmbrole.getSelectedItem().toString();
	}



	public void setUserNameTextField(String value) {
		txtusername.setText(value);
	}
	public void setFirstNameTextField(String value){
		txtfirstname.setText(value);
	}
	public void setLastNameTextField(String value){
		txtlastname.setText(value);
	}
	public void setEmailTextField(String value){
		txtemailid.setText(value);
	}
	public void setPasswordTextField(String value){
		txtpassword.setText(value);
	}
	public void setConfirmPasswordTextField(String value){
		txtconfirmpassword.setText(value);
	}
	public void setPhoneNumberTextField(String value){
		txtphonenumber.setText(value);
	}


	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistrationGUI().setVisible(true);
			}
		});
	}

	public JComboBox getCmbrole() {
		return cmbrole;
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton btnsignup;
	private javax.swing.JComboBox cmbrole;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lblconfirmpassword;
	private javax.swing.JLabel lblemailid;
	private javax.swing.JLabel lblfirstname;
	private javax.swing.JLabel lbllastname;
	private javax.swing.JLabel lblpassword;
	private javax.swing.JLabel lblphonenumber;
	private javax.swing.JLabel lblrole;
	private javax.swing.JLabel lblusername;
	private javax.swing.JPasswordField txtconfirmpassword;
	private javax.swing.JTextField txtemailid;
	private javax.swing.JTextField txtfirstname;
	private javax.swing.JTextField txtlastname;
	private javax.swing.JPasswordField txtpassword;
	private javax.swing.JTextField txtphonenumber;
	private javax.swing.JTextField txtusername;
	private javax.swing.JLabel imgLabel;

	// End of variables declaration                   
}
