package package1;

import java.awt.CardLayout;

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author karnati_sruti
 */
public class AdminHomeGUI extends javax.swing.JFrame {

	/**
	 * Creates new form Admin
	 */
	public AdminHomeGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		topPanel = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		lblWelcome = new javax.swing.JLabel();
		btnLogout = new javax.swing.JButton();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		SearchPanel = new javax.swing.JPanel();
		lblSearch = new javax.swing.JLabel();
		rbtnTeamMember = new javax.swing.JRadioButton();
		rtbnProject = new javax.swing.JRadioButton();
		btnSearch = new javax.swing.JButton();
		TeamPanel = new javax.swing.JPanel();
		MemberPanel = new javax.swing.JPanel();
		ForumPanel = new javax.swing.JPanel();
		TeamRbtnSearchPanel = new javax.swing.JPanel();
		ProjectRbtnSearchPanel = new javax.swing.JPanel();
		txtParticipantName = new javax.swing.JTextField();
		txtProjectName = new javax.swing.JTextField();
		lblParticpantName = new javax.swing.JLabel();
		lblProjectName = new javax.swing.JLabel();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 190, Short.MAX_VALUE)
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 76, Short.MAX_VALUE)
				);

		lblWelcome.setText("Hi, welcome ");

		btnLogout.setText("Logout");

		jTabbedPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

		SearchPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		lblSearch.setText("Search");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
		
		buttonGroup1.add(rbtnTeamMember);
		rbtnTeamMember.setText("By Team Member");

		buttonGroup1.add(rtbnProject);
		rtbnProject.setText("By Project");

		btnSearch.setText("Search");
		lblParticpantName.setText("Participant Name");
		lblProjectName.setText("Project Name");

		javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
		SearchPanel.setLayout(SearchPanelLayout);
		SearchPanelLayout.setHorizontalGroup(
				SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(SearchPanelLayout.createSequentialGroup()
						.addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(SearchPanelLayout.createSequentialGroup()
										.addContainerGap()
										.addComponent(lblSearch))
										.addGroup(SearchPanelLayout.createSequentialGroup()
												.addGap(76, 76, 76)
												.addComponent(rbtnTeamMember)
												.addGap(59, 59, 59)
												.addComponent(rtbnProject)
												.addGap(115, 115, 115)
												.addComponent(btnSearch)))
												.addContainerGap(301, Short.MAX_VALUE))
				);
		SearchPanelLayout.setVerticalGroup(
				SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(SearchPanelLayout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addComponent(lblSearch)
						.addGap(18, 18, 18)
						.addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(rbtnTeamMember)
										.addComponent(rtbnProject))
										.addComponent(btnSearch))
										.addContainerGap(227, Short.MAX_VALUE))
				);

		jTabbedPane2.addTab("Search", SearchPanel);

		javax.swing.GroupLayout TeamPanelLayout = new javax.swing.GroupLayout(TeamPanel);
		TeamPanel.setLayout(TeamPanelLayout);
		TeamPanelLayout.setHorizontalGroup(
				TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 802, Short.MAX_VALUE)
				);
		TeamPanelLayout.setVerticalGroup(
				TeamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 413, Short.MAX_VALUE)
				);

		jTabbedPane2.addTab("Team", TeamPanel);

		javax.swing.GroupLayout MemberPanelLayout = new javax.swing.GroupLayout(MemberPanel);
		MemberPanel.setLayout(MemberPanelLayout);
		MemberPanelLayout.setHorizontalGroup(
				MemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 802, Short.MAX_VALUE)
				);
		MemberPanelLayout.setVerticalGroup(
				MemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 413, Short.MAX_VALUE)
				);

		jTabbedPane2.addTab("Member", MemberPanel);

		javax.swing.GroupLayout ForumPanelLayout = new javax.swing.GroupLayout(ForumPanel);
		ForumPanel.setLayout(ForumPanelLayout);
		ForumPanelLayout.setHorizontalGroup(
				ForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 802, Short.MAX_VALUE)
				);
		ForumPanelLayout.setVerticalGroup(
				ForumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 413, Short.MAX_VALUE)
				);

		jTabbedPane2.addTab("Forum", ForumPanel);

		javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
		topPanel.setLayout(topPanelLayout);
		topPanelLayout.setHorizontalGroup(
				topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(topPanelLayout.createSequentialGroup()
										.addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 59, Short.MAX_VALUE))
										.addGroup(topPanelLayout.createSequentialGroup()
												.addComponent(lblWelcome)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnLogout)
												.addGap(46, 46, 46))
												.addGroup(topPanelLayout.createSequentialGroup()
														.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				);
		topPanelLayout.setVerticalGroup(
				topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(topPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(19, 19, 19)
						.addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblWelcome)
								.addComponent(btnLogout))
								.addGap(18, 18, 18)
								.addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(38, Short.MAX_VALUE))
				);

		lblWelcome.getAccessibleContext().setAccessibleName("Hi, welcome ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 23, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>  

	private void rbtnTeamMemberActionPerformed(java.awt.event.ActionEvent evt) {                                               
		// TODO add your handling code here:


	}

	private void rtbnProjectActionPerformed(java.awt.event.ActionEvent evt) {                                            
		// TODO add your handling code here:
		SearchPanel.add(new JLabel("Hi Sruti"));
		//SearchPanel.add(lblProjectName);
		//SearchPanel.add(txtProjectName);
	}


	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
		// TODO add your handling code here:
		if(rbtnTeamMember.isSelected()) {
			/*TeamRbtnSearchPanel.add(lblParticpantName);
			TeamRbtnSearchPanel.add(txtParticipantName);
			TeamRbtnSearchPanel.validate();
			TeamRbtnSearchPanel.repaint();
			TeamRbtnSearchPanel.setVisible(true);
			SearchPanel.add(TeamRbtnSearchPanel);*/
			SearchPanel.validate();
			SearchPanel.repaint();
			
		} else if(rtbnProject.isSelected()) {
			SearchPanel.add(ProjectRbtnSearchPanel);
		}
	}

	/**
	 * @param args the command line arguments
	 */


	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminHomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminHomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminHomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminHomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AdminHomeGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify                     
	private javax.swing.JPanel ForumPanel;
	private javax.swing.JPanel MemberPanel;
	private javax.swing.JPanel SearchPanel;
	private javax.swing.JPanel TeamPanel;
	private javax.swing.JButton btnLogout;
	private javax.swing.JButton btnSearch;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JLabel lblSearch;
	private javax.swing.JLabel lblWelcome;
	private javax.swing.JRadioButton rbtnTeamMember;
	private javax.swing.JRadioButton rtbnProject;
	private javax.swing.JPanel topPanel;
	private javax.swing.JPanel TeamRbtnSearchPanel;
	private javax.swing.JPanel ProjectRbtnSearchPanel;
	private javax.swing.JTextField txtParticipantName;
	private javax.swing.JTextField txtProjectName;
	private javax.swing.JLabel lblParticpantName;
	private javax.swing.JLabel lblProjectName;
	// End of variables declaration                   
}
